"""initial feedback schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_feedback";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("feedback",sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_by_user_id",sa.String(36),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("location",sa.String(200),nullable=False),sa.Column("department",sa.String(120),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True),nullable=True),sa.Column("assigned_staff_id",sa.String(36),nullable=True),sa.Column("ai_category",sa.String(30),nullable=True),sa.Column("ai_category_confidence",sa.Float(),nullable=True),sa.Column("ai_sentiment",sa.String(30),nullable=True),sa.Column("ai_sentiment_confidence",sa.Float(),nullable=True),sa.Column("ai_priority",sa.String(30),nullable=True),sa.Column("ai_priority_confidence",sa.Float(),nullable=True),sa.Column("ai_model_version",sa.String(80),nullable=True),sa.Column("ai_needs_review",sa.Boolean(),nullable=False),sa.Column("final_category",sa.String(30),nullable=True),sa.Column("final_priority",sa.String(30),nullable=True),sa.Column("human_override",sa.Boolean(),nullable=False),sa.Column("override_reason",sa.Text(),nullable=True),sa.Column("decision_source",sa.String(30),nullable=False),sa.Column("ai_analysis_state",sa.String(20),nullable=False))
 for name,cols in [("ix_feedback_creator",["created_by_user_id"]),("ix_feedback_status",["status"]),("ix_feedback_priority",["final_priority"]),("ix_feedback_category",["final_category"]),("ix_feedback_staff",["assigned_staff_id"]),("ix_feedback_created",["created_at"])]:op.create_index(name,"feedback",cols)
 op.create_table("comments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("feedback_id",sa.String(36),nullable=False),sa.Column("user_id",sa.String(36),nullable=False),sa.Column("user_role",sa.String(20),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_comments_feedback","comments",["feedback_id"])
 op.create_table("status_history",sa.Column("id",sa.String(36),primary_key=True),sa.Column("feedback_id",sa.String(36),nullable=False),sa.Column("from_status",sa.String(30),nullable=True),sa.Column("to_status",sa.String(30),nullable=False),sa.Column("changed_by_user_id",sa.String(36),nullable=False),sa.Column("changed_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_status_history_feedback","status_history",["feedback_id"])
 op.create_table("audit",sa.Column("id",sa.String(36),primary_key=True),sa.Column("actor_user_id",sa.String(36),nullable=False),sa.Column("action",sa.String(80),nullable=False),sa.Column("resource_type",sa.String(40),nullable=False),sa.Column("resource_id",sa.String(36),nullable=False),sa.Column("metadata_json",sa.Text(),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_audit_timestamp","audit",["timestamp"]);op.create_index("ix_audit_action","audit",["action"])
def downgrade():
 for table in ["audit","status_history","comments","feedback"]:op.drop_table(table)
